from google import genai
from google.genai import errors
from src.config.settings import get_api_key

# Prompt defined as a constant
SYSTEM_INSTRUCTION = (
    "You are a helpful and intelligent chatbot helper. Analyze the chat history "
    "provided by the user and suggest an appropriate response. "
    "Respond with only the text content of your reply. Do not include sender formatting, "
    "timestamps, or extra context."
)

class GeminiReplyGenerator:
    """
    A class to generate reply messages using Google's Gemini Models.
    
    This class handles client initialization, system prompts configuration,
    and reply generation with robust error handling.
    """
    
    def __init__(self, model_name: str = "gemini-2.5-flash") -> None:
        """
        Initializes the Gemini client using the API key loaded from configurations.
        
        Args:
            model_name (str): The name of the Gemini model to use. Defaults to 'gemini-2.5-flash'.
        """
        api_key = get_api_key()
        self.client = genai.Client(api_key=api_key)
        self.model_name = model_name

    def generate_reply(self, chat_history: str) -> str:
        """
        Generates a reply based on the provided chat history.
        
        Args:
            chat_history (str): The raw conversation logs or chat history.
            
        Returns:
            str: The text reply generated by the Gemini model.
            
        Raises:
            ValueError: If the input chat_history is empty.
            RuntimeError: If there is an issue calling the Gemini API or generating content.
        """
        if not chat_history or not chat_history.strip():
            raise ValueError("Input chat_history cannot be empty.")

        try:
            # Call the official Google Gen AI SDK models endpoint
            response = self.client.models.generate_content(
                model=self.model_name,
                contents=chat_history,
                config={
                    'system_instruction': SYSTEM_INSTRUCTION,
                    'temperature': 0.7,
                }
            )

            # Check if response contains valid text
            if response.text:
                return response.text.strip()
            else:
                raise ValueError("The model returned an empty response.")

        except errors.APIError as e:
            # Handle specific API errors raised by the SDK
            raise RuntimeError(
                f"Gemini API Error (Code: {e.code}): {e.message}"
            ) from e
        except Exception as e:
            # Handle generic or unexpected errors
            raise RuntimeError(
                f"An unexpected error occurred during reply generation: {str(e)}"
            ) from e
